import { container } from "../Container.js";
import ActionRegistry from "../game/actions/ActionRegistry.js";
import { ActionDefinition } from "../game/actions/ActionDefinition.js";

/**
 * Built-in actions the player spends action points on each year. Age gates
 * keep the list age-appropriate; the action panel filters by the player's age.
 */
const ACTION_DEFS: ActionDefinition[] = [
  {
    id: "act_play",
    labelKey: "action.play",
    descKey: "action.play.desc",
    icon: "🎈",
    apCost: 1,
    minAge: 3,
    maxAge: 12,
    effects: { happiness: 8, fitness: 2, social: 1 },
  },
  {
    id: "act_study",
    labelKey: "action.study",
    descKey: "action.study.desc",
    icon: "📚",
    apCost: 1,
    minAge: 6,
    maxAge: 60,
    effects: { intelligence: 4, happiness: -1 },
  },
  {
    id: "act_read",
    labelKey: "action.read",
    descKey: "action.read.desc",
    icon: "📖",
    apCost: 1,
    minAge: 6,
    effects: { intelligence: 2, happiness: 1 },
  },
  {
    id: "act_exercise",
    labelKey: "action.exercise",
    descKey: "action.exercise.desc",
    icon: "🏃",
    apCost: 1,
    minAge: 5,
    effects: { fitness: 4, health: 1, happiness: 1 },
  },
  {
    id: "act_social",
    labelKey: "action.social",
    descKey: "action.social.desc",
    icon: "👥",
    apCost: 1,
    minAge: 8,
    effects: { social: 4, happiness: 2 },
    relationship: { npc: "npc_friend", delta: 4 },
  },
  {
    id: "act_rest",
    labelKey: "action.rest",
    descKey: "action.rest.desc",
    icon: "🛌",
    apCost: 1,
    effects: { health: 3, happiness: 2, weakValue: -3 },
  },
  {
    id: "act_parttime",
    labelKey: "action.parttime",
    descKey: "action.parttime.desc",
    icon: "🧾",
    apCost: 1,
    minAge: 14,
    maxAge: 24,
    effects: { money: 20, social: 1, fitness: -1 },
  },
  {
    id: "act_work",
    labelKey: "action.work",
    descKey: "action.work.desc",
    icon: "💼",
    apCost: 1,
    minAge: 18,
    maxAge: 68,
    effects: { money: 60, happiness: -2, fitness: -1 },
    relationship: { npc: "npc_boss", delta: 2 },
  },
  {
    id: "act_meditate",
    labelKey: "action.meditate",
    descKey: "action.meditate.desc",
    icon: "🧘",
    apCost: 1,
    minAge: 10,
    effects: { depressionValue: -5, angerValue: -4, happiness: 2 },
    buff: { id: "fx_focus", turns: 3 },
  },
  {
    id: "act_invest",
    labelKey: "action.invest",
    descKey: "action.invest.desc",
    icon: "📈",
    apCost: 1,
    minAge: 20,
    requires: [{ prop: "money", gte: 100 }],
    effects: { money: -100, happiness: -1 },
    buff: { id: "fx_blessed", turns: 5 },
  },
  {
    id: "act_volunteer",
    labelKey: "action.volunteer",
    descKey: "action.volunteer.desc",
    icon: "🤝",
    apCost: 1,
    minAge: 12,
    requires: [{ prop: "money", gte: 20 }],
    effects: { money: -20, social: 3, happiness: 3 },
  },
  {
    id: "act_walk",
    labelKey: "action.walk",
    descKey: "action.walk.desc",
    icon: "🚶",
    apCost: 1,
    minAge: 50,
    effects: { health: 2, happiness: 2, fitness: 1 },
  },
  {
    id: "act_reminisce",
    labelKey: "action.reminisce",
    descKey: "action.reminisce.desc",
    icon: "🖼",
    apCost: 1,
    minAge: 55,
    effects: { happiness: 3, depressionValue: -2 },
  },
  {
    id: "act_visit_family",
    labelKey: "action.visitFamily",
    descKey: "action.visitFamily.desc",
    icon: "🏠",
    apCost: 1,
    minAge: 6,
    effects: { happiness: 4 },
    relationship: { npc: "npc_mom", delta: 5 },
  },
  {
    id: "act_network",
    labelKey: "action.network",
    descKey: "action.network.desc",
    icon: "🤝",
    apCost: 1,
    minAge: 18,
    effects: { social: 4, happiness: 1 },
    relationship: { npc: "npc_colleague", delta: 5 },
  },
  {
    id: "act_date",
    labelKey: "action.date",
    descKey: "action.date.desc",
    icon: "🌹",
    apCost: 1,
    minAge: 18,
    requires: [{ npc: "npc_partner", gte: 30 }],
    effects: { happiness: 6, social: 2 },
    relationship: { npc: "npc_partner", delta: 8 },
  },
  {
    id: "act_care_child",
    labelKey: "action.careChild",
    descKey: "action.careChild.desc",
    icon: "🧸",
    apCost: 1,
    minAge: 25,
    requires: [{ npc: "npc_child", gte: 20 }],
    effects: { happiness: 6 },
    relationship: { npc: "npc_child", delta: 8 },
  },
  {
    id: "act_gamble",
    labelKey: "action.gamble",
    descKey: "action.gamble.desc",
    icon: "🎲",
    apCost: 1,
    minAge: 18,
    requires: [{ prop: "money", gte: 50 }],
    effects: { money: -50, happiness: 3 },
    buff: { id: "fx_fortune", turns: 3 },
  },
  {
    id: "act_therapy",
    labelKey: "action.therapy",
    descKey: "action.therapy.desc",
    icon: "🛋",
    apCost: 1,
    minAge: 16,
    requires: [{ prop: "money", gte: 80 }],
    effects: { money: -80, depressionValue: -15, angerValue: -10 },
    buff: { id: "fx_calm", turns: 3 },
  },
  {
    id: "act_help",
    labelKey: "action.help",
    descKey: "action.help.desc",
    icon: "🤲",
    apCost: 1,
    minAge: 10,
    effects: { happiness: 3, reputation: 4 },
  },
  {
    id: "act_speech",
    labelKey: "action.speech",
    descKey: "action.speech.desc",
    icon: "🎤",
    apCost: 1,
    minAge: 18,
    requires: [{ prop: "social", gte: 30 }],
    effects: { social: 3, reputation: 6 },
  },
  {
    id: "act_contribute",
    labelKey: "action.contribute",
    descKey: "action.contribute.desc",
    icon: "🎗",
    apCost: 1,
    minAge: 18,
    requires: [{ prop: "money", gte: 150 }],
    effects: { money: -150, reputation: 10, happiness: 4 },
  },
  {
    id: "act_showoff",
    labelKey: "action.showoff",
    descKey: "action.showoff.desc",
    icon: "🕶",
    apCost: 1,
    minAge: 18,
    requires: [{ prop: "money", gte: 200 }],
    effects: { money: -200, happiness: 2, reputation: -6 },
  },
  {
    id: "act_job_clerk",
    labelKey: "action.jobClerk",
    descKey: "action.jobClerk.desc",
    icon: "🏢",
    apCost: 1,
    minAge: 18,
    effects: { money: 20 },
    career: "career_clerk",
  },
  {
    id: "act_job_teacher",
    labelKey: "action.jobTeacher",
    descKey: "action.jobTeacher.desc",
    icon: "🎓",
    apCost: 1,
    minAge: 20,
    requires: [{ prop: "intelligence", gte: 25 }],
    effects: { money: 20 },
    career: "career_teacher",
  },
  {
    id: "act_job_artist",
    labelKey: "action.jobArtist",
    descKey: "action.jobArtist.desc",
    icon: "🎨",
    apCost: 1,
    minAge: 16,
    effects: { money: 10, happiness: 3 },
    career: "career_artist",
  },
  {
    id: "act_job_engineer",
    labelKey: "action.jobEngineer",
    descKey: "action.jobEngineer.desc",
    icon: "🛠",
    apCost: 1,
    minAge: 20,
    requires: [{ prop: "intelligence", gte: 30 }],
    effects: { money: 20 },
    career: "career_engineer",
  },
  {
    id: "act_job_trader",
    labelKey: "action.jobTrader",
    descKey: "action.jobTrader.desc",
    icon: "📦",
    apCost: 1,
    minAge: 18,
    requires: [{ prop: "money", gte: 100 }],
    effects: { money: 25 },
    career: "career_trader",
  },
];

export default class Actions {
  private static init = false;

  public static load(): void {
    if (this.init) return;
    this.init = true;
    const reg = container.resolve(ActionRegistry);
    for (const def of ACTION_DEFS) {
      if (!reg.has(def.id)) reg.register(def);
    }
  }
}
